//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace work0420.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class newsDB
    {
        public int no { get; set; }
        public string date { get; set; }
        public string time { get; set; }
        public string title { get; set; }
        public string urlwith { get; set; }
        public string state { get; set; }
        public string wherefrom { get; set; }
    }
}
